### ISSUE TITLE
Change Font-family and font-size?

### ISSUE THREAD

**Issue by clFaster** [AlexTorresSk/custom-electron-titlebar#24]
Hi,

I'm tried out this nice package and I was wondering if there is a fast way to change the font-family and font-size?

It's a very nice package!

BR

**Comment by AlexTorresSk** [comment]
You can assign the font and size globally with `body` in your CSS styles.

Also only to the title bar using `.titlebar` and `.titlebar > *`

Example:

```css
// Applied to every document including the title bar
body {
    font-family: Roboto, sans-serif;
}
```
Or

```css
// It only applies to the title bar
.titlebar, .titlebar > * {
    font-family: Roboto, sans-serif;
    font-size: 20px;
}
```
