### ISSUE TITLE
Change color for windows-control icons

### ISSUE THREAD

**Issue by talhaanees** [AlexTorresSk/custom-electron-titlebar#34]
Is there any possible way, through CSS or JS, where I can change the color for windows controls icons? 
I tried overriding the SVG through CSS, but it didn't work. Couldn't find anything regarding controls style as well in the API.

**Comment by AlexTorresSk** [comment]
That is not possible in this version or in previous versions, I will work very soon to fix it.

**Comment by talhaanees** [comment]
That's alright. Thank-you so much for the response!

**Comment by AlexTorresSk** [comment]
You can use this css:

```css
.titlebar .window-controls-container .window-icon {
    background-color: your_color;
}
```

While I work in a better solution
