### ISSUE TITLE
!important in -webkit-mask-size

### ISSUE THREAD

**Issue by adriankiezik** [AlexTorresSk/custom-electron-titlebar#80]
in .window-icon css selector there is -webkit-mask-size: 23.1% with !important.
Because of this !important we can't override this property to change icon size.
Can you do something with this?

**Comment by AlexTorresSk** [comment]
This property is important, since the size of the minimize, maximize and close icons should not change.

But I will consider the suggestion and remove this property of the style.

**Comment by ThibaudPerrin** [comment]
It is possible to override this property by giving the selector a higher specificity, for example `body` here  
```css
body .titlebar .window-controls-container .window-icon-bg .window-icon {
    -webkit-mask-size: 40% !important;
    mask-size: 40% !important;
}
``` 
[source](https://stackoverflow.com/a/11178731)
